// GENERATED by scripts/bakeRoutePaths.ts — do not edit by hand.
// Regenerate after changing routes, ports, coastline, or the projection
// reference latitude:  npx tsx scripts/bakeRoutePaths.ts
//
// Each route's real sailing path — the visibility-graph pathfind around the
// coastline plus validated corner-smoothing (sim/seaRoute.ts) — baked so the
// browser renders it directly instead of computing it on first map load.
import type { Point } from '../sim/geography'

export const ROUTE_PATHS: Record<string, Point[]> = {
  'wemyss-bay-rothesay': [{ x: -288.281, y: 6220.996 }, { x: -297.903, y: 6215.363 }],
  'ardrossan-brodick': [{ x: -283.727, y: 6194.212 }, { x: -303.867, y: 6186.731 }],
  'gourock-dunoon': [{ x: -284.177, y: 6228.773 }, { x: -290.594, y: 6228.443 }],
  'kennacraig-port-ellen': [{ x: -322.892, y: 6212.023 }, { x: -355.301, y: 6196.683 }, { x: -364.757, y: 6193.099 }],
  'kennacraig-port-askaig': [{ x: -322.892, y: 6212.023 }, { x: -355.113, y: 6198.836 }, { x: -360.197, y: 6216.999 }],
  'tayinloan-ardminish': [{ x: -334.165, y: 6195.762 }, { x: -339.196, y: 6196.817 }],
  'tarbert-portavadie': [{ x: -319.47, y: 6218.697 }, { x: -313.258, y: 6219.838 }],
  'claonaig-lochranza': [{ x: -318.148, y: 6206.892 }, { x: -312.355, y: 6201.081 }],
  'oban-colonsay': [{ x: -322.797, y: 6279.784 }, { x: -332.575, y: 6268.775 }, { x: -365.152, y: 6241.712 }],
  'port-askaig-colonsay': [{ x: -360.197, y: 6216.999 }, { x: -365.152, y: 6241.712 }],
  'oban-lismore': [{ x: -322.797, y: 6279.784 }, { x: -324.12, y: 6290.817 }],
}
