/**
 * Bakes every route's real sailing path (the visibility-graph pathfind
 * around the coastline, then the validated corner-smoothing) into a static
 * data file, `src/map/routePaths.ts`, so the browser never runs the
 * pathfinding at load time. Same discipline as the coastline/depth-contour
 * data: computed once offline, committed, regenerated when the inputs
 * change.
 *
 * Run it after adding/moving a route, adding a region, or changing the
 * coastline or the projection reference latitude:
 *
 *     npx tsx scripts/bakeRoutePaths.ts   (or: npm run bake:routes)
 *
 * A test (routePaths.test.ts) guards that every route in ALL_ROUTES has a
 * baked path, so a forgotten regeneration fails CI rather than silently
 * falling back to live computation in the browser.
 */
import { writeFileSync } from 'node:fs'
import { fileURLToPath } from 'node:url'
import { dirname, join } from 'node:path'
import { ALL_COASTLINE, ALL_ROUTES, findPort } from '../src/map/regions'
import { projectPort } from '../src/sim/geography'
import { findSeaRoute } from '../src/sim/seaRoute'

const round = (n: number) => Math.round(n * 1000) / 1000

const entries: string[] = []
let totalPoints = 0
for (const route of ALL_ROUTES) {
  const a = findPort(route.portAId)
  const b = findPort(route.portBId)
  if (!a || !b) {
    console.error(`skipping ${route.id}: unknown port`)
    continue
  }
  const path = findSeaRoute(projectPort(a), projectPort(b), ALL_COASTLINE)
  totalPoints += path.length
  const pts = path.map((p) => `{ x: ${round(p.x)}, y: ${round(p.y)} }`).join(', ')
  entries.push(`  '${route.id}': [${pts}],`)
}

const source = `// GENERATED by scripts/bakeRoutePaths.ts — do not edit by hand.
// Regenerate after changing routes, ports, coastline, or the projection
// reference latitude:  npx tsx scripts/bakeRoutePaths.ts
//
// Each route's real sailing path — the visibility-graph pathfind around the
// coastline plus validated corner-smoothing (sim/seaRoute.ts) — baked so the
// browser renders it directly instead of computing it on first map load.
import type { Point } from '../sim/geography'

export const ROUTE_PATHS: Record<string, Point[]> = {
${entries.join('\n')}
}
`

const outPath = join(dirname(fileURLToPath(import.meta.url)), '..', 'src', 'map', 'routePaths.ts')
writeFileSync(outPath, source)
console.log(`baked ${entries.length} route paths (${totalPoints} points) → src/map/routePaths.ts`)
