import type { ShipDesign } from './types'

/** First-pass recreations of the hero ships, eyeballed from the reference
 * photos. Expect these to be hand-tuned in the builder over time. */
export const HERO_SHIPS: ShipDesign[] = [
  {
    name: 'Isle of Arran',
    lengthM: 85,
    bow: 'raked',
    stern: 'open',
    superstructure: {
      decks: 2,
      startFrac: 0.15,
      endFrac: 0.85,
      upperStartFrac: 0.34,
      upperEndFrac: 0.76,
      bridge: 'classic',
      windows: 'rect',
    },
    funnel: { style: 'classic', count: 2, posFrac: 0.59, baseWidth: 4.2, topWidth: 2.9, height: 7.8, baseDeckDrop: 1 },
    masts: { foremast: true, mainmast: true, aftDerrick: true, mainmastFrac: 0.8, derrickFrac: 0.3 },
    lifeboats: { count: 2, posFrac: 0.63 },
    hull: { portholes: true, bowThruster: true, webAddress: true },
  },
  {
    name: 'Isle of Mull',
    lengthM: 90,
    bow: 'raked',
    stern: 'open',
    superstructure: { decks: 2, startFrac: 0.14, endFrac: 0.76, bridge: 'classic', windows: 'mixed' },
    funnel: { style: 'classic', count: 1, posFrac: 0.68, baseWidth: 5.4, topWidth: 3.4, height: 5.0 },
    masts: { foremast: true, mainmast: false, aftDerrick: true },
    lifeboats: { count: 2, posFrac: 0.52 },
    hull: { portholes: true, bowThruster: true, webAddress: true },
  },
  {
    name: 'Lord of the Isles',
    lengthM: 85,
    bow: 'raked',
    stern: 'gantry',
    superstructure: { decks: 2, startFrac: 0.15, endFrac: 0.63, bridge: 'classic', windows: 'mixed' },
    funnel: { style: 'classic', count: 2, posFrac: 0.6, baseWidth: 3.0, topWidth: 2.2, height: 6.2 },
    masts: { foremast: true, mainmast: true, aftDerrick: false },
    lifeboats: { count: 2, posFrac: 0.42 },
    hull: { portholes: true, bowThruster: true, webAddress: true },
  },
  {
    name: 'Caledonian Isles',
    lengthM: 94,
    bow: 'flared',
    stern: 'enclosed',
    superstructure: {
      decks: 2,
      startFrac: 0.07,
      endFrac: 0.93,
      bridge: 'classic',
      windows: 'rect',
    },
    funnel: {
      style: 'flick',
      count: 1,
      posFrac: 0.62,
      baseWidth: 5.6,
      topWidth: 3.2,
      height: 6.8,
      baseDeckDrop: 1,
    },
    masts: {
      foremast: true,
      mainmast: true,
      aftDerrick: false,
      mainmastFrac: 0.53,
      mainmastStyle: 'dark-raked',
    },
    lifeboats: { count: 2, posFrac: 0.5 },
    hull: { portholes: true, bowThruster: true, webAddress: true },
  },
  {
    name: 'Clansman',
    lengthM: 99,
    bow: 'flared',
    stern: 'enclosed',
    superstructure: { decks: 2, startFrac: 0.12, endFrac: 0.88, bridge: 'classic', windows: 'rect' },
    funnel: { style: 'raked', count: 1, posFrac: 0.84, baseWidth: 4.8, topWidth: 4.0, height: 5.8 },
    masts: { foremast: true, mainmast: false, aftDerrick: false },
    lifeboats: { count: 2, posFrac: 0.66 },
    hull: { portholes: false, bowThruster: true, webAddress: true },
  },
  {
    name: 'Hebrides',
    lengthM: 99,
    bow: 'flared',
    stern: 'enclosed',
    superstructure: { decks: 2, startFrac: 0.12, endFrac: 0.87, bridge: 'classic', windows: 'rect' },
    funnel: { style: 'raked', count: 1, posFrac: 0.82, baseWidth: 4.8, topWidth: 4.0, height: 5.8 },
    masts: { foremast: true, mainmast: true, aftDerrick: false },
    lifeboats: { count: 2, posFrac: 0.64 },
    hull: { portholes: false, bowThruster: true, webAddress: true },
  },
  {
    name: 'Isle of Lewis',
    lengthM: 101,
    bow: 'flared',
    stern: 'enclosed',
    superstructure: { decks: 2, startFrac: 0.1, endFrac: 0.85, bridge: 'classic', windows: 'rect' },
    funnel: { style: 'raked', count: 1, posFrac: 0.8, baseWidth: 5.0, topWidth: 3.8, height: 5.6 },
    masts: { foremast: true, mainmast: true, aftDerrick: false },
    lifeboats: { count: 2, posFrac: 0.6 },
    hull: { portholes: true, bowThruster: true, webAddress: true },
  },
  {
    name: 'Loch Seaforth',
    lengthM: 116,
    bow: 'modern',
    stern: 'enclosed',
    superstructure: { decks: 3, startFrac: 0.1, endFrac: 0.9, bridge: 'modern', windows: 'rect' },
    funnel: { style: 'modern', count: 2, posFrac: 0.58, baseWidth: 3.4, topWidth: 3.2, height: 5.0 },
    masts: { foremast: false, mainmast: true, aftDerrick: false },
    lifeboats: { count: 1, posFrac: 0.74 },
    hull: { portholes: false, bowThruster: true, webAddress: true },
  },
  {
    name: 'Lochnevis',
    lengthM: 49,
    bow: 'raked',
    stern: 'gantry',
    superstructure: { decks: 1, startFrac: 0.2, endFrac: 0.62, bridge: 'classic', windows: 'rect' },
    funnel: { style: 'classic', count: 1, posFrac: 0.56, baseWidth: 2.4, topWidth: 2.0, height: 4.8 },
    masts: { foremast: true, mainmast: false, aftDerrick: false },
    lifeboats: { count: 1, posFrac: 0.46 },
    hull: { portholes: false, bowThruster: false, webAddress: true },
  },
]

export const DEFAULT_DESIGN: ShipDesign = HERO_SHIPS[0]
